"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { Avatar, AvatarGroup, Logo, StatusBadge } from "./ui";
import { Icon } from "./icon";
import { FAQ } from "./faq";
import { useWorkspace, updateWorkspace } from "@/lib/store";
import { projectProgress } from "@/lib/workspace";
import { MomentumChart, Portfolio } from "./workspace";

export default function Landing() {
  const { data, ready } = useWorkspace();
  const [menuOpen, setMenuOpen] = useState(false);
  const tasks = data.projects.flatMap(project => project.tasks.map(task => ({ ...task, projectId: project.id, projectName: project.name })));
  const previewTasks = [...tasks.filter(t => !t.done), ...tasks.filter(t => t.done)].slice(0, 4);
  const completed = tasks.filter(t => t.done).length;
  return <div className="landing-page">
    <a className="skip-link" href="#main-content">Skip to content</a>
    <div className="announcement">Good work starts with a little clarity.<span className="announcement-divider"/><Link href="/workspace">Meet your workspace<Icon name="arrow" size={14}/></Link></div>
    <header className="landing-header"><div className="landing-nav"><Link className="logo-link" href="/" aria-label="Operly home"><Logo/></Link><nav aria-label="Main navigation" className={menuOpen ? "landing-links landing-links-open" : "landing-links"}><a href="#features" onClick={() => setMenuOpen(false)}>Features</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><a href="#pricing" onClick={() => setMenuOpen(false)}>Plans</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQs</a></nav><div className="landing-nav-actions"><Link className="plain-link" href="/workspace">Open workspace</Link><Link className="button button-primary" href="/workspace">Try Operly free<Icon name="arrow" size={16}/></Link><button className="icon-button landing-menu" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><Icon name={menuOpen ? "close" : "menu"}/></button></div></div></header>
    <main aria-busy={!ready} id="main-content" className="landing-main">
      <section className="landing-hero" aria-labelledby="hero-heading"><div className="hero-grid-art" aria-hidden="true"/><div className="hero-copy"><span className="section-tag"><span/>Your everyday workspace</span><h1 id="hero-heading">Less busywork.<br/>More good work.</h1><p>Bring your projects, tasks, and people together.<br className="desktop-break"/> A little more clarity for whatever comes next.</p><div className="hero-actions"><Link className="button button-primary" href="/workspace">Open workspace<Icon name="arrow" size={17}/></Link><Link className="button button-secondary" href="/workspace?tour=1">Try a demo</Link></div><span className="hero-footnote">Free to explore. No account or credit card needed.</span></div>
        <div className="hero-atmosphere" aria-hidden="true"/>
        <div className="hero-preview" id="preview"><section className="preview-card preview-tasks"><div className="preview-heading"><h2>Your next small steps</h2><span className="live-label"><span/>Demo</span></div><div className="preview-task-list">{previewTasks.map(task => <label className={`preview-task ${task.done ? "preview-task-done" : ""}`} key={task.id}><span className="preview-task-top"><input type="checkbox" checked={task.done} disabled={!ready} onChange={() => updateWorkspace(w => ({ ...w, projects: w.projects.map(p => {if(p.id !== task.projectId) return p; const nextTasks = p.tasks.map(t => t.id === task.id ? { ...t, done: !t.done } : t); return { ...p, tasks: nextTasks, status: nextTasks.every(t=>t.done) ? "Completed" : p.status === "Completed" ? "In progress" : p.status };}), activity: [{ id: crypto.randomUUID(), text: `${task.done ? "Reopened" : "Completed"} “${task.title}” from the preview`, date: new Date().toISOString(), kind: "task" as const }, ...w.activity].slice(0,200) }))}/><strong>{task.title}</strong></span><span className="preview-task-bottom"><span>{task.projectName}</span><span className="photo-avatar-group">{[1,2,3].map(n => <Image key={n} src={`/design/avatar-${n}.png`} alt="" width={24} height={24}/>)}</span></span></label>)}</div></section>
        <section className="preview-card preview-momentum"><div className="preview-heading"><h2>Good things are moving</h2><Link href="/workspace" className="icon-button" aria-label="Open project overview"><Icon name="external" size={17}/></Link></div><MomentumChart projects={data.projects}/><div className="preview-chart-footer"><span><span className="tiny-dot"/>Real progress from your demo projects</span><span>{completed}/{tasks.length}</span></div></section>
        <section className="preview-card preview-breakdown"><div className="preview-heading"><h2>The bigger picture</h2></div><Portfolio projects={data.projects}/><div className="portfolio-legend">{(["In progress", "In review", "Completed"] as const).map(status => <div key={status}><span className={`legend-dot legend-${status.toLowerCase().replaceAll(" ", "-")}`}/><span>{status}</span><strong>{data.projects.filter(p => p.status === status).length}</strong></div>)}</div><Link href="/projects" className="button button-secondary">View projects<Icon name="arrow" size={14}/></Link></section></div>
      </section>
      <div className="landing-divider" aria-hidden="true"/>
      <section className="product-principles" aria-label="Workspace essentials"><span>A simpler kind of productive.</span><div><span><Icon name="projects"/>Projects with a purpose</span><span><Icon name="check"/>One step at a time</span><span><Icon name="team"/>People, together</span><span><Icon name="activity"/>Progress you can see</span></div></section>
      <div className="landing-divider" aria-hidden="true"/>
      <section id="features" className="landing-section features-section"><div className="landing-section-heading"><span className="section-tag"><span/>Thoughtfully simple</span><h2>Everything in its place.</h2><p>Less looking for things. More getting things done.<br/>The everyday essentials, brought together.</p></div><div className="feature-main"><div className="feature-copy"><h3>Big ideas.<br/>Manageable steps.</h3><p>Set a date, bring in your team, and turn the next big thing into a clear plan, one small task at a time.</p><Link className="button button-primary" href="/projects">Explore projects<Icon name="arrow" size={16}/></Link></div><div className="feature-project-preview"><div className="preview-heading"><h3>Projects, with a little perspective</h3><Icon name="projects" size={18}/></div>{data.projects.slice(0, 3).map(p => <Link href="/projects" key={p.id} className="feature-project-row"><span aria-hidden="true" className={`project-symbol tone-${p.color}`}>{p.name[0]}</span><span><strong>{p.name}</strong><small>{p.category}</small></span><StatusBadge status={p.status}/><span className="feature-project-percent">{projectProgress(p)}%</span></Link>)}<div className="feature-preview-footer"><AvatarGroup members={data.members}/><span>A shared sense of direction.</span></div></div></div>
        <div className="feature-secondary-grid"><article><div className="feature-visual feature-team-visual"><div className="preview-heading"><h3>Your people, in one place</h3><Icon name="team" size={18}/></div>{data.members.slice(0,3).map(m => <div className="feature-member" key={m.id}><Avatar member={m}/><div><strong>{m.name}</strong><span>{m.role === "Admin" ? "Keeping things moving" : "Making good things happen"}</span></div><span className="member-check"><Icon name="check" size={14}/></span></div>)}</div><h3>A place for the whole team.</h3><p>Keep your people close to the work. Assign project teammates and give every idea the right pair of hands.</p></article><article><div className="feature-visual feature-progress-visual"><div className="preview-heading"><h3>Every little step counts</h3><Icon name="activity" size={18}/></div><div className="feature-progress-value">{tasks.length ? Math.round(completed/tasks.length*100) : 0}<span>%</span></div><span className="feature-progress-caption">of demo tasks completed</span><div className="feature-bars" aria-hidden="true">{data.projects.map(p => <div key={p.id}><span style={{ height: `${Math.max(6,projectProgress(p))}%` }}/><small>{p.name.split(" ")[0]}</small></div>)}</div><span className="feature-progress-note">A little progress is still progress.</span></div><h3>Clarity without the check-ins.</h3><p>See completed tasks, project progress, and workspace updates in one overview. Know where things stand at a glance.</p></article></div>
      </section>
      <div className="landing-divider" aria-hidden="true"/>
      <section className="how-section landing-section" id="how-it-works"><div><span className="section-tag"><span/>A fresh start</span><h2>Your next good day<br/>starts here.</h2><p>No setup marathon. Just open the workspace<br/>and make yourself at home.</p><Link href="/workspace" className="text-link">Take a look around<Icon name="arrow" size={17}/></Link></div><ol><li><span>01</span><div><h3>Make a little space</h3><p>Create a project for whatever you’re working on.</p></div></li><li><span>02</span><div><h3>Find your next step</h3><p>Add tasks, set a deadline, and bring in your people.</p></div></li><li><span>03</span><div><h3>Keep good things moving</h3><p>Check off tasks and watch the bigger picture take shape.</p></div></li></ol></section>
      <div className="landing-divider" aria-hidden="true"/>
      <section className="landing-section landing-pricing" id="pricing"><div className="landing-section-heading"><span className="section-tag"><span/>Room to grow</span><h2>Plans for Every Team</h2><p>Explore the plan that fits your way of working.<br/>These are demo plans. There’s nothing to pay.</p></div><div className="landing-plan-grid">{(["Starter", "Team"] as const).map(plan => <article className="landing-plan" key={plan}><div className="landing-plan-header"><h3>{plan}</h3>{plan === "Team" && <span className="plan-tag">Better together</span>}</div><p>{plan === "Starter" ? "A home for your everyday work." : "More room for your growing team."}</p><div className="plan-price">{plan === "Starter" ? "$0" : "$12"}<span>{plan === "Starter" ? "/ forever" : "/ member / month"}</span></div><ul>{(plan === "Starter" ? ["Projects and task checklists", "Your team, in one place", "Workspace activity", "Export your data anytime"] : ["Everything in Starter", "Unlimited demo projects", "Team roles and assignments", "A shared place to plan"]).map(feature => <li key={feature}><span><Icon name="check" size={12}/></span>{feature}</li>)}</ul><Link href="/billing" className={`button ${plan === "Team" ? "button-primary" : "button-secondary"}`}>Explore {plan}<Icon name="arrow" size={16}/></Link></article>)}</div></section>
      <div className="landing-divider" aria-hidden="true"/>
      <section className="landing-section faq-section" id="faq"><div className="landing-section-heading"><span className="section-tag"><span/>A little more clarity</span><h2>Good questions.<br className="mobile-break"/> Straight answers.</h2><p>A few things to know before you make yourself at home.</p></div><FAQ/></section>
      <div className="landing-divider" aria-hidden="true"/>
    </main>
    <footer className="landing-footer"><div className="footer-cta"><div><span className="section-tag"><span/>One less thing to juggle</span><h2>Make room<br/>for good work.</h2></div><div><Link className="button button-primary" href="/workspace">Step into your workspace<Icon name="arrow" size={18}/></Link><p>No sign-up. No rush. Just a little clarity.</p></div></div><div className="footer-bottom"><Link href="/" aria-label="Operly home"><Logo/></Link><span>A calmer way to work.</span><div><a href="#features">Features</a><a href="#faq">FAQs</a><Link href="/workspace">Workspace</Link></div><span>© {new Date().getFullYear()} Operly</span></div></footer>
  </div>;
}
