"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { SearchDialog, useSearchShortcut } from "./search-dialog";
import { HelpDialog } from "./help-dialog";
import { GuidedTour, useGuidedTour } from "./guided-tour";
import { useEffect, useState, type FormEvent } from "react";
import { Icon, type IconName } from "./icon";
import { Avatar, AvatarGroup, EmptyState, Logo, Modal, StatusBadge } from "./ui";
import { useWorkspace, updateWorkspace } from "@/lib/store";
import { createWorkspace, formatDate, initials, projectProgress, type Activity, type Project, type WorkspaceData } from "@/lib/workspace";

export type View = "Overview" | "Projects" | "Team" | "Activity" | "Settings" | "Billing";
type Dialog = "create" | "member" | "search" | "help" | "reset" | "delete" | null;
const navigation: { title: View; href: string; icon: IconName }[] = [
  { title: "Overview", href: "/workspace", icon: "overview" }, { title: "Projects", href: "/projects", icon: "projects" }, { title: "Team", href: "/team", icon: "team" }, { title: "Activity", href: "/activity", icon: "activity" },
  { title: "Settings", href: "/settings", icon: "settings" }, { title: "Billing", href: "/billing", icon: "billing" },
];
function log(data: WorkspaceData, text: string, kind: Activity["kind"]): WorkspaceData {
  return { ...data, activity: [{ id: crypto.randomUUID(), text, date: new Date().toISOString(), kind }, ...data.activity].slice(0, 200) };
}

export default function Workspace({ view = "Overview" }: { view?: View }) {
  const { data, ready, error } = useWorkspace();
  const router = useRouter();
  const shortcutLabel = useSearchShortcut();
  const tour = useGuidedTour(ready, view === "Overview");
  const [checklistFocus, setChecklistFocus] = useState(false);
  const [dialog, setDialog] = useState<Dialog>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All projects");
  const [layout, setLayout] = useState<"list" | "grid">("list");
  const [toast, setToast] = useState("");
  const [memberError, setMemberError] = useState("");
  const [range, setRange] = useState("All projects");
  const selected = data.projects.find(p => p.id === selectedId);
  const tasks = data.projects.flatMap(p => p.tasks);
  const completedTasks = tasks.filter(t => t.done).length;
  const activeProjects = data.projects.filter(p => p.status !== "Completed");
  const visibleProjects = data.projects.filter(p => (filter === "All projects" || p.status === filter) && `${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
  const currentMember = { ...data.members[0], name: data.userName, initials: initials(data.userName) };

  useEffect(() => {
    function shortcut(event: KeyboardEvent) {
      if (!(event.metaKey || event.ctrlKey) || event.key.toLowerCase() !== "k" || event.altKey || event.shiftKey || event.isComposing) return;
      if (!ready || selectedId || (dialog && dialog !== "search")) return;
      event.preventDefault();
      if (dialog === "search") document.querySelector<HTMLInputElement>('[role="combobox"][aria-label="Search projects or pages"]')?.focus();
      else { setMobileOpen(false); setDialog("search"); }
    }
    window.addEventListener("keydown", shortcut);
    return () => window.removeEventListener("keydown", shortcut);
  }, [dialog, selectedId, ready]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(""), 4500); return () => clearTimeout(timer); }, [toast]);
  function commit(update: (workspace: WorkspaceData) => WorkspaceData, message: string) { updateWorkspace(update); setToast(message); }
  function closeDialog() { setDialog(null); setMemberError(""); }
  function openProject(id: string, checklist = false) { setChecklistFocus(checklist); setSelectedId(id); setDialog(null); }
  function navigate(href: string) { closeDialog(); setMobileOpen(false); router.push(href); }
  function finishTour() { tour.setStep(null); document.querySelector<HTMLHeadingElement>(".page-heading h1")?.focus(); }
  function restartTour() { closeDialog(); if (view === "Overview") { tour.setStep(0); requestAnimationFrame(() => document.getElementById("tour-heading")?.focus()); } else navigate("/workspace?tour=1"); }
  function createProject(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const name = String(form.get("name")).trim(); if (!name) return;
    const project: Project = { id: crypto.randomUUID(), name, description: String(form.get("description")).trim(), category: String(form.get("category")), color: String(form.get("color")), status: "In progress", dueDate: String(form.get("dueDate")), memberIds: [data.members[0].id], tasks: [] };
    commit(workspace => log({ ...workspace, projects: [project, ...workspace.projects] }, `${data.userName} created “${name}”`, "project"), "Project created"); setDialog(null); setChecklistFocus(false); setSelectedId(project.id);
  }
  function addMember(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const email = String(form.get("email")).trim().toLowerCase(); const name = String(form.get("name")).trim();
    if (!name) { setMemberError("Enter a name for this teammate."); return; }
    if (data.members.some(m => m.email.toLowerCase() === email)) { setMemberError("A teammate with this email already exists."); return; }
    commit(workspace => log({ ...workspace, members: [...workspace.members, { id: crypto.randomUUID(), name, email, role: "Member", initials: initials(name), color: "sage" }] }, `${name} was added to the workspace`, "team"), "Teammate added to this demo workspace"); closeDialog();
  }
  function toggleTask(taskId: string) {
    if (!selected) return;
    commit(workspace => {
      const projects = workspace.projects.map(p => { if(p.id !== selected.id) return p; const nextTasks = p.tasks.map(t => t.id === taskId ? { ...t, done: !t.done } : t); return { ...p, tasks: nextTasks, status: nextTasks.every(t => t.done) ? "Completed" as const : p.status === "Completed" ? "In progress" as const : p.status }; });
      const task = selected.tasks.find(t => t.id === taskId);
      return log({ ...workspace, projects }, `${data.userName} ${task?.done ? "reopened" : "completed"} “${task?.title}”`, "task");
    }, "Task updated");
  }
  function exportWorkspace() { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "operly-workspace.json"; anchor.click(); URL.revokeObjectURL(url); setToast("Workspace exported"); }

  const projectRows = (projects: Project[]) => <div className="project-table-wrap"><table className="project-table"><thead><tr><th>Project name</th><th>Status</th><th>Team</th><th>Progress</th><th>Due date</th><th><span className="sr-only">Open project</span></th></tr></thead><tbody>{projects.map(p => <tr key={p.id}><td><button className="project-name-button" onClick={() => openProject(p.id)}><span aria-hidden="true" className={`project-symbol tone-${p.color}`}>{p.name.slice(0, 1)}</span><span><strong>{p.name}</strong><small>{p.category}</small></span></button></td><td><StatusBadge status={p.status}/></td><td><AvatarGroup members={data.members.filter(m => p.memberIds.includes(m.id))}/></td><td><div className="table-progress"><span className="progress-track"><span style={{ width: `${projectProgress(p)}%` }}/></span><span>{projectProgress(p)}%</span></div></td><td className="date-cell">{formatDate(p.dueDate)}</td><td><button className="icon-button" aria-label={`Open ${p.name}`} onClick={() => openProject(p.id)}><Icon name="chevron" size={16}/></button></td></tr>)}</tbody></table></div>;
  const activityList = (limit?: number) => <div className="activity-list">{data.activity.slice(0, limit).map(item => <div className="activity-item" key={item.id}><span className={`activity-icon activity-${item.kind}`}><Icon name={item.kind === "task" ? "check" : item.kind === "team" ? "team" : item.kind === "settings" ? "settings" : "projects"} size={15}/></span><div><p>{item.text}</p><time dateTime={item.date}>{new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", timeZone: ready ? undefined : "UTC" }).format(new Date(item.date))}</time></div></div>)}</div>;

  return <div className="app-shell">
    <a className="skip-link" href="#main-content">Skip to content</a>
    {mobileOpen && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={() => setMobileOpen(false)}/>}
    <aside className={`sidebar ${mobileOpen ? "sidebar-open" : ""}`}><Link href="/" className="logo-link" aria-label="Operly home"><Logo/></Link>
      <Link href="/settings" className="workspace-switch"><span className="workspace-monogram">S</span><span><strong>{data.name}</strong><small>Personal workspace</small></span><Icon name="chevron" size={14} className="rotate-down"/></Link>
      <span className="nav-label">WORKSPACE</span><nav aria-label="Main navigation">{navigation.slice(0, 4).map(item => <Link key={item.title} href={item.href} className={`nav-link ${view === item.title ? "nav-active" : ""}`} aria-current={view === item.title ? "page" : undefined}><Icon name={item.icon}/><span>{item.title}</span>{item.title === "Projects" && <span className="nav-count">{data.projects.length}</span>}{item.title === "Overview" && view === item.title && <span className="active-dot"/>}</Link>)}</nav>
      <span className="nav-label second-label">MANAGE</span><nav aria-label="Workspace management">{navigation.slice(4).map(item => <Link key={item.title} href={item.href} className={`nav-link ${view === item.title ? "nav-active" : ""}`} aria-current={view === item.title ? "page" : undefined}><Icon name={item.icon}/><span>{item.title}</span></Link>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-note"><span className="note-spark" aria-hidden="true">✳</span><h3>A little more room to grow.</h3><p>Explore the Team plan for your next chapter.</p><Link href="/billing">Explore plans <Icon name="arrow" size={16}/></Link></div><button className="help-link" disabled={!ready} onClick={() => { if (mobileOpen) document.querySelector<HTMLButtonElement>(".mobile-menu")?.focus(); setMobileOpen(false); setDialog("help"); }}><Icon name="help" size={18}/>Help & getting started<Icon name="external" size={14}/></button><Link href="/settings" className="user-profile"><Avatar member={currentMember}/><span><strong>{data.userName}</strong><small>Workspace admin</small></span><Icon name="chevron" size={16}/></Link></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Icon name="menu"/></button><span>Workspace</span><Icon name="chevron" size={13}/><strong>{view}</strong></div><div className="header-actions"><button className="search-trigger" aria-label="Search projects or pages" aria-keyshortcuts={shortcutLabel === "⌘ K" ? "Meta+k" : "Control+k"} disabled={!ready} onClick={() => setDialog("search")}><Icon name="search" size={17}/><span>Search projects or pages</span><kbd>{shortcutLabel}</kbd></button><Link href="/activity" className="icon-button notification-button" aria-label="View activity"><Icon name="bell"/><span/></Link><span className="header-divider"/><Link href="/settings" aria-label="Your profile"><Avatar member={currentMember} small/></Link></div></header>
      <main aria-busy={!ready} id="main-content" className="main-content">
        {error && <div className="storage-warning" role="alert">{error}</div>}
        <div className="page-heading"><div>{view === "Overview" ? <><div className="greeting"><span className="greeting-line"/>YOUR WORK, AT A GLANCE</div><h1 tabIndex={-1}>Let’s make good things happen<span className="heading-dot">.</span></h1><p>Welcome back, {data.userName.split(" ")[0]}. Here’s what’s happening in your workspace.</p></> : <><div className="greeting"><span className="greeting-line"/>YOUR WORKSPACE</div><h1 tabIndex={-1}>{view}<span className="heading-dot">.</span></h1><p>{({ Projects: "A home for every idea, from the first step to the finish line.", Team: "Good work starts with good people. Keep your team together.", Activity: "The small steps that move your work forward.", Settings: "Make this workspace feel like yours.", Billing: "The right amount of room for the way you work." } as Record<string, string>)[view]}</p></> }</div>{(view === "Overview" || view === "Projects") && <button className="button button-primary" disabled={!ready} onClick={() => setDialog("create")}><Icon name="plus" size={18}/>New project</button>}{view === "Team" && <button className="button button-primary" disabled={!ready} onClick={() => setDialog("member")}><Icon name="plus" size={18}/>Add teammate</button>}</div>

        {view === "Overview" && <>
          {tour.step !== null && <GuidedTour step={tour.step} onStep={tour.setStep} project={data.projects[0]} onOpenProject={openProject} onCreateProject={() => setDialog("create")} onProgress={() => { const progress = document.getElementById("workspace-progress"); progress?.scrollIntoView({ block: "center", behavior: "auto" }); progress?.focus({ preventScroll: true }); }} onClose={finishTour}/>}
          <div className="stats-strip"><Stat label="Active projects" value={activeProjects.length} icon="projects" detail={`${data.projects.filter(p => p.status === "In review").length} ready for review`}/><Stat label="Tasks completed" value={completedTasks} icon="check" detail={`of ${tasks.length} total tasks`} positive/><Stat label="Overall progress" value={`${tasks.length ? Math.round(completedTasks / tasks.length * 100) : 0}%`} icon="activity" detail="Every little step counts"/><Stat label="Team members" value={data.members.length} icon="team" detail="Working better, together"/></div>
          <div className="overview-grid"><section className="panel project-health" id="workspace-progress" tabIndex={-1} aria-label="Project momentum"><div className="section-heading"><div><h2>Project momentum</h2><p>A little progress, every day.</p></div><label className="select-wrap"><span className="sr-only">Projects in chart</span><select value={range} onChange={e => setRange(e.target.value)}><option>All projects</option><option>Active projects</option></select></label></div><MomentumChart projects={range === "Active projects" ? activeProjects : data.projects}/></section>
          <section className="panel portfolio-panel"><div className="section-heading"><div><h2>Project breakdown</h2><p>A place for everything.</p></div><Icon name="overview" size={18}/></div><Portfolio projects={data.projects}/><div className="portfolio-legend">{(["In progress", "In review", "Completed"] as const).map(status => <div key={status}><span className={`legend-dot legend-${status.toLowerCase().replaceAll(" ", "-")}`}/><span>{status}</span><strong>{data.projects.filter(p => p.status === status).length}</strong></div>)}</div></section>
          <section className="panel recent-projects"><div className="section-heading"><div><h2>Your projects <span className="subtle-count">{data.projects.length}</span></h2><p>The things you’re moving forward.</p></div><Link className="text-link" href="/projects">View all projects<Icon name="arrow" size={16}/></Link></div>{data.projects.length ? projectRows(data.projects.slice(0, 4)) : <EmptyState title="Your next idea starts here" description="Create a project and give your work a place to grow." action={<button className="button button-primary" onClick={() => setDialog("create")}>New project</button>}/>}</section>
          <section className="panel recent-activity"><div className="section-heading"><h2>Recent activity</h2><Link href="/activity" className="icon-button" aria-label="View all activity"><Icon name="arrow" size={17}/></Link></div>{activityList(4)}<Link href="/activity" className="activity-footer">See all activity<Icon name="arrow" size={15}/></Link></section></div>
          <div className="workspace-footer"><span><span className="tiny-dot"/> A little more organized. A lot more possible.</span><span>Sample workspace · Saved in your browser</span></div>
        </>}

        {view === "Projects" && <section className="panel"><div className="project-toolbar"><div className="filter-tabs" role="group" aria-label="Filter projects">{["All projects", "In progress", "In review", "Completed"].map(status => <button className={filter === status ? "filter-active" : ""} key={status} aria-pressed={filter === status} onClick={() => setFilter(status)}>{status}<span>{data.projects.filter(p => status === "All projects" || p.status === status).length}</span></button>)}</div><div className="project-tools"><label className="inline-search"><Icon name="search" size={17}/><input placeholder="Find a project..." aria-label="Find a project" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="layout-toggle"><button className="icon-button" aria-label="List view" aria-pressed={layout === "list"} onClick={() => setLayout("list")}><Icon name="list" size={18}/></button><button className="icon-button" aria-label="Grid view" aria-pressed={layout === "grid"} onClick={() => setLayout("grid")}><Icon name="grid" size={18}/></button></div></div></div>{!visibleProjects.length ? <EmptyState title="No projects here yet" description={query ? "Try a different search or create a new project." : "Create a project or choose another status."}/> : layout === "list" ? projectRows(visibleProjects) : <div className="project-card-grid">{visibleProjects.map(p => <button className="project-card" key={p.id} onClick={() => openProject(p.id)}><div className="project-card-top"><span aria-hidden="true" className={`project-symbol tone-${p.color}`}>{p.name[0]}</span><StatusBadge status={p.status}/></div><h3>{p.name}</h3><p>{p.description || "Ready for your next idea."}</p><div className="project-card-progress"><span>Progress</span><strong>{projectProgress(p)}%</strong></div><span className="progress-track"><span style={{width: `${projectProgress(p)}%`}}/></span><div className="project-card-bottom"><AvatarGroup members={data.members.filter(m => p.memberIds.includes(m.id))}/><span>{formatDate(p.dueDate)}</span></div></button>)}</div>}</section>}

        {view === "Team" && <><div className="info-note"><Icon name="team" size={18}/><p>This is your demo team. Adding a teammate stores their details locally; no email invitation is sent.</p></div><section className="panel"><div className="section-heading"><h2>People in your workspace <span className="subtle-count">{data.members.length}</span></h2><span className="muted">Everyone has a part to play.</span></div><div className="member-list">{data.members.map((m, index) => <div className="member-row" key={m.id}><Avatar member={m}/><div className="member-info"><strong>{index === 0 ? data.userName : m.name}{index === 0 && <span className="you-label">You</span>}</strong><span>{m.email}</span></div>{index === 0 ? <span className="role-label">Admin</span> : <><label><span className="sr-only">Role for {m.name}</span><select value={m.role} onChange={e => commit(w => log({ ...w, members: w.members.map(person => person.id === m.id ? { ...person, role: e.target.value as "Admin" | "Member" } : person) }, `${m.name}’s role was updated`, "team"), "Role updated")}><option>Member</option><option>Admin</option></select></label><button className="icon-button" aria-label={`Remove ${m.name}`} onClick={() => commit(w => log({ ...w, members: w.members.filter(person => person.id !== m.id), projects: w.projects.map(p => ({ ...p, memberIds: p.memberIds.filter(id => id !== m.id) })) }, `${m.name} was removed from the workspace`, "team"), "Teammate removed")}><Icon name="close" size={16}/></button></>}</div>)}</div></section></>}

        {view === "Activity" && <section className="panel full-activity"><div className="section-heading"><div><h2>Workspace activity</h2><p>Project updates, completed tasks, and new faces.</p></div><span className="subtle-count">{data.activity.length} updates</span></div>{data.activity.length ? activityList() : <EmptyState title="A fresh start" description="Your team’s activity will appear here as you work."/>}</section>}

        {view === "Settings" && <div className="settings-layout"><section className="panel"><div className="section-heading"><div><h2>Workspace details</h2><p>The basics that make it your own.</p></div></div><form className="settings-form form-stack" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); const name = String(form.get("workspaceName")).trim(); const userName = String(form.get("userName")).trim(); if(!name || !userName) return; commit(w => log({ ...w, name, userName, members: w.members.map((m,i) => i === 0 ? { ...m, name: userName, initials: initials(userName) } : m) }, "Workspace details were updated", "settings"), "Changes saved"); }}><label>Workspace name<input required name="workspaceName" maxLength={60} defaultValue={data.name} key={data.name}/></label><label>Your name<input required name="userName" maxLength={60} defaultValue={data.userName} key={data.userName}/></label><label>Email address<input disabled value={data.members[0].email} readOnly/><span className="field-hint">This demo has no connected authentication provider.</span></label><div className="form-actions"><button className="button button-primary" type="submit">Save changes</button></div></form></section><section className="panel data-settings"><div className="section-heading"><div><h2>Your data</h2><p>Stored locally, under your control.</p></div></div><div className="settings-row"><div><h3>Export workspace</h3><p>Download your projects, team, and activity as JSON.</p></div><button className="button button-secondary" onClick={exportWorkspace}><Icon name="download" size={16}/>Export</button></div><div className="settings-row"><div><h3>Reset demo workspace</h3><p>Replace current data with the original sample workspace.</p></div><button className="button button-danger-outline" onClick={() => setDialog("reset")}>Reset demo</button></div></section></div>}

        {view === "Billing" && <><div className="info-note"><Icon name="billing" size={18}/><p>Plan selection is a demo. No payment is collected and no subscription is created.</p></div><div className="plans-grid">{(["Starter", "Team"] as const).map(plan => <section className={`panel plan-card ${plan === "Team" ? "plan-featured" : ""}`} key={plan}><div className="plan-top"><span className="eyebrow">{plan === "Starter" ? "FIND YOUR RHYTHM" : "GROW TOGETHER"}</span>{data.plan === plan && <span className="current-plan">Current demo plan</span>}</div><h2>{plan}</h2><p>{plan === "Starter" ? "A thoughtful space to organize your everyday work." : "A little more space for bigger ideas and growing teams."}</p><div className="plan-price">{plan === "Starter" ? "$0" : "$12"}<span>{plan === "Starter" ? "/ forever" : "/ member / month"}</span></div><span className="field-hint">Illustrative pricing for this demo</span><ul>{(plan === "Starter" ? ["Projects and task checklists", "Team directory", "Workspace activity", "Local data export"] : ["Everything in Starter", "Unlimited demo projects", "Team roles and assignments", "A shared place to plan"]).map(feature => <li key={feature}><Icon name="check" size={17}/>{feature}</li>)}</ul><button className={`button ${plan === "Team" ? "button-primary" : "button-secondary"}`} disabled={data.plan === plan} onClick={() => commit(w => log({ ...w, plan }, `Demo plan changed to ${plan}`, "settings"), `${plan} demo plan selected`)}>{data.plan === plan ? "Your current plan" : `Try ${plan} in demo`}<Icon name="arrow" size={16}/></button></section>)}</div><p className="billing-footnote">Simple by design. Connect a billing provider when you’re ready for real subscriptions.</p></>}
      </main>
    </div>
    {toast && <div className="toast" role="status"><span><Icon name="check" size={16}/></span>{toast}<button className="icon-button" aria-label="Dismiss notification" onClick={() => setToast("")}><Icon name="close" size={15}/></button></div>}

    {dialog === "create" && <Modal title="Make room for a new project" onClose={closeDialog} initialFocus='input[name="name"]'><p className="modal-description">Start with a name. The rest can take shape as you go.</p><form className="form-stack" onSubmit={createProject}><label>Project name<input name="name" placeholder="What are you working on?" required maxLength={80} autoFocus/></label><label>Description <span className="optional">Optional</span><textarea name="description" placeholder="A little context for your team" maxLength={500} rows={3}/></label><div className="form-two-col"><label>Category<select name="category"><option>Design</option><option>Branding</option><option>Marketing</option><option>Engineering</option><option>Operations</option></select></label><label>Due date<input type="date" name="dueDate" defaultValue="2026-10-30" required/></label></div><label>Project color<select name="color"><option value="sage">Sage</option><option value="sand">Sand</option><option value="lavender">Lavender</option><option value="blue">Blue</option><option value="rose">Rose</option></select></label><div className="form-actions"><button type="button" className="button button-secondary" onClick={closeDialog}>Cancel</button><button className="button button-primary" type="submit"><Icon name="plus" size={17}/>Create project</button></div></form></Modal>}
    {dialog === "member" && <Modal title="Good work is better together" onClose={closeDialog} initialFocus='input[name="name"]'><p className="modal-description">Add a teammate to this local workspace. No invitation email will be sent.</p><form className="form-stack" onSubmit={addMember}><label>Full name<input autoFocus name="name" placeholder="Teammate’s name" required maxLength={60}/></label><label>Email address<input name="email" type="email" placeholder="name@company.com" required maxLength={120}/></label>{memberError && <p className="form-error" role="alert">{memberError}</p>}<div className="form-actions"><button type="button" className="button button-secondary" onClick={closeDialog}>Cancel</button><button type="submit" className="button button-primary">Add teammate</button></div></form></Modal>}
    {dialog === "search" && <SearchDialog projects={data.projects} pages={navigation} onClose={closeDialog} onOpenProject={openProject} onNavigate={navigate}/>}
    {dialog === "help" && <HelpDialog onClose={closeDialog} onCreateProject={() => setDialog("create")} onNavigate={navigate} onRestartTour={restartTour} shortcut={shortcutLabel}/>}
    {dialog === "reset" && <Modal title="Start fresh?" onClose={closeDialog}><p className="modal-description">This replaces your local projects, team, settings, and activity with the sample workspace. Export your current workspace first if you want to keep it.</p><div className="form-actions"><button className="button button-secondary" onClick={exportWorkspace}>Export first</button><button className="button button-danger" onClick={() => {commit(() => createWorkspace(), "Demo workspace reset"); closeDialog();}}>Reset workspace</button></div></Modal>}
    {dialog === "delete" && selected && <Modal title="Delete this project?" onClose={() => setDialog(null)}><p className="modal-description">“{selected.name}” and its tasks will be removed from this local workspace.</p><div className="form-actions"><button className="button button-secondary" onClick={() => setDialog(null)}>Keep project</button><button className="button button-danger" onClick={() => {commit(w => log({ ...w, projects: w.projects.filter(p => p.id !== selected.id) }, `“${selected.name}” was deleted`, "project"), "Project deleted"); setSelectedId(null); setDialog(null);}}>Delete project</button></div></Modal>}
    {selected && !dialog && <Modal title={selected.name} wide initialFocus={checklistFocus ? "[data-checklist-heading]" : undefined} onClose={() => setSelectedId(null)}><ProjectDetail key={selected.id} project={selected} data={data} toggleTask={toggleTask} onDelete={() => setDialog("delete")} onUpdate={(update, message) => commit(w => log({ ...w, projects: w.projects.map(p => p.id === selected.id ? update(p) : p) }, message, "project"), "Project updated")}/></Modal>}
  </div>;
}

function Stat({ label, value, icon, detail, positive = false }: { label: string; value: string | number; icon: IconName; detail: string; positive?: boolean }) { return <div className="stat"><div className="stat-label"><span>{label}</span><Icon name={icon} size={18}/></div><strong className="stat-value">{value}</strong><span className={`stat-detail ${positive ? "stat-positive" : ""}`}>{positive && <Icon name="check" size={13}/>} {detail}</span></div>; }

export function MomentumChart({ projects }: { projects: Project[] }) {
  const chartProjects = projects.slice(0, 8);
  const chartWidth = 580;
  const columnWidth = chartWidth / Math.max(chartProjects.length, 1);
  return <div className="momentum-chart"><div className="chart-summary"><strong>{projects.flatMap(p => p.tasks).filter(t => t.done).length}<span> tasks completed</span></strong><span className="chart-key"><span/>Completed<span className="key-remaining"/>Remaining</span></div><svg viewBox="0 0 650 220" role="img" aria-label="Completed and remaining task percentages by project"><title>Project task completion</title>{[0, 25, 50, 75, 100].map(value => <g key={value}><text x="0" y={175 - value * 1.45} className="chart-axis">{value}%</text><line x1="43" y1={172 - value * 1.45} x2="637" y2={172 - value * 1.45} className="chart-grid-line"/></g>)}{chartProjects.map((p,i) => { const progress = projectProgress(p); const x = 46 + columnWidth * i + columnWidth * .25; return <g key={p.id}><title>{`${p.name}: ${progress}% completed, ${p.tasks.length} tasks`}</title><rect x={x} y="27" width={Math.min(columnWidth * .46, 60)} height="145" rx="5" className="chart-bar-remaining"/><rect x={x} y={172 - progress * 1.45} width={Math.min(columnWidth * .46, 60)} height={progress * 1.45} rx="5" className="chart-bar-completed"/><text x={x + Math.min(columnWidth * .46, 60) / 2} y="197" textAnchor="middle" className="chart-axis">{p.name.split(" ")[0].slice(0, 10)}</text></g>;})}</svg>{!projects.length && <span className="chart-empty">Create a project to start tracking progress.</span>}</div>;
}

export function Portfolio({ projects }: { projects: Project[] }) {
  let offset = 0;
  const circumference = 2 * Math.PI * 62;
  return <div className="portfolio-chart"><svg viewBox="0 0 170 170" role="img" aria-label={`${projects.length} projects: ${projects.filter(p => p.status === "In progress").length} in progress, ${projects.filter(p => p.status === "In review").length} in review, ${projects.filter(p => p.status === "Completed").length} completed`}><circle cx="85" cy="85" r="62" className="donut-track"/>{(["In progress", "In review", "Completed"] as const).map(status => { const fraction = projects.length ? projects.filter(p => p.status === status).length / projects.length : 0; const segmentOffset = offset; offset += fraction; return <circle key={status} cx="85" cy="85" r="62" className={`donut-segment donut-${status.toLowerCase().replaceAll(" ", "-")}`} strokeDasharray={`${Math.max(0, fraction * circumference - 5)} ${circumference}`} strokeDashoffset={-segmentOffset * circumference} transform="rotate(-90 85 85)"/>; })}</svg><div className="donut-label"><strong>{projects.length}</strong><span>Total projects</span></div></div>;
}

function ProjectDetail({ project, data, toggleTask, onDelete, onUpdate }: { project: Project; data: WorkspaceData; toggleTask: (id: string) => void; onDelete: () => void; onUpdate: (update: (project: Project) => Project, message: string) => void }) {
  const [editing, setEditing] = useState(false);
  const [taskTitle, setTaskTitle] = useState("");
  return <div className="project-detail">{editing ? <form className="form-stack" onSubmit={e => {e.preventDefault(); const form = new FormData(e.currentTarget); const name = String(form.get("name")).trim(); if (!name) return; onUpdate(p => ({ ...p, name, description: String(form.get("description")).trim(), dueDate: String(form.get("dueDate")) }), `“${name}” details were updated`); setEditing(false);}}><label>Project name<input name="name" required maxLength={80} defaultValue={project.name}/></label><label>Description<textarea name="description" rows={3} maxLength={500} defaultValue={project.description}/></label><label>Due date<input type="date" name="dueDate" required defaultValue={project.dueDate}/></label><div className="form-actions"><button className="button button-secondary" type="button" onClick={() => setEditing(false)}>Cancel</button><button type="submit" className="button button-primary">Save details</button></div></form> : <><div className="detail-top"><span aria-hidden="true" className={`project-symbol tone-${project.color}`}>{project.name[0]}</span><div><span className="eyebrow">{project.category}</span><p>{project.description || "Add a description to give your team a little context."}</p></div></div><div className="detail-metadata"><label>Status<select value={project.status} onChange={e => { const status = e.target.value as Project["status"]; onUpdate(p => ({ ...p, status, tasks: status === "Completed" ? p.tasks.map(t => ({ ...t, done: true })) : p.tasks }), `“${project.name}” moved to ${status.toLowerCase()}`);}}><option>In progress</option><option>In review</option><option>Completed</option></select></label><div><span>Due date</span><strong><Icon name="calendar" size={16}/>{formatDate(project.dueDate)}</strong></div><button className="button button-secondary" onClick={() => setEditing(true)}>Edit details</button></div><div className="detail-progress"><div><strong>Project progress</strong><span>{projectProgress(project)}%</span></div><span className="progress-track"><span style={{ width: `${projectProgress(project)}%` }}/></span></div></>}
    <div className="detail-section"><h3 tabIndex={-1} data-checklist-heading>The next small steps <span className="subtle-count">{project.tasks.filter(t => t.done).length}/{project.tasks.length}</span></h3><div className="task-list">{project.tasks.map(task => <label className={`task-row ${task.done ? "task-done" : ""}`} key={task.id}><input type="checkbox" checked={task.done} onChange={() => toggleTask(task.id)}/><span>{task.title}</span></label>)}</div><form className="add-task-form" onSubmit={e => {e.preventDefault(); const title = taskTitle.trim(); if(!title) return; onUpdate(p => ({ ...p, status: p.status === "Completed" ? "In progress" : p.status, tasks: [...p.tasks, { id: crypto.randomUUID(), title, done: false }] }), `A task was added to “${project.name}”`); setTaskTitle("");}}><input placeholder="Add a new task..." aria-label="New task title" value={taskTitle} onChange={e => setTaskTitle(e.target.value)} required maxLength={120}/><button className="button button-secondary" type="submit" aria-label="Add task"><Icon name="plus" size={17}/>Add</button></form></div>
    <div className="detail-section"><h3>Project team</h3><div className="assignment-list">{data.members.map(member => <label className="assignment" key={member.id}><input type="checkbox" checked={project.memberIds.includes(member.id)} onChange={e => {const checked = e.target.checked; onUpdate(p => ({ ...p, memberIds: checked ? [...p.memberIds, member.id] : p.memberIds.filter(id => id !== member.id) }), `“${project.name}” team was updated`);}}/><Avatar member={member} small/><span>{member.name}</span></label>)}</div></div><div className="detail-bottom"><span className="muted">Saved to this browser</span><button className="danger-text" onClick={onDelete}>Delete project</button></div>
  </div>;
}
